systemd: remove configuration to default DHCP on management interface
bisdn/meta-switch pull request #14
Opened 2021-09-21 10:00 UTC by rubensfig

The switch from Yocto warrior to Yocto dunfell brought in a default
wired config /lib/systemd/networkd/80-wired.network, which configures
DHCP on all interfaces starting with eth and en. Since 80 is lower number
than 99, it matches first, and thus always takes precedence before our
99-enp.network, preventing any intended management interface config
from being applied.

Removing the file we package with systemd removes the duplicated
configuration to allow the pre-packaged file taking precendence and applying
the DHCP configuration.

Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>

2021-09-21 13:47 UTC, jklare commented
please link the file 80-wired.network from the source code that you mentioned here in your commit message

2021-09-24 08:35 UTC, KanjiMonster requested changes
Please squash your commits.

> Removing the file we package with systemd removes the duplicated
configuration to allow the pre-packaged file taking precendence and applying
the DHCP configuration.

This is contradicting the previous paragraph, which states that the pre-packaged file is already taking precedence. 

This also needs an explanation why we think the pre-packaged (80-)wired.network is good enough, and we do not need to ship our own anymore.

2021-09-24 08:36 UTC, KanjiMonster commented
This breaks the pipelines, can you take care of updating the test?

2021-09-29 08:44 UTC, KanjiMonster commented
Two small nitpicks:

Commit subject should state that the config isn't needed anymore, currently it sounds like we decided to not configure DHCP anymore. E.g. something like "systemd: drop redundant management interface config file".

Add a small one or two sentence paragrah at the beginning of the commit message paraphrasing the change, then go into detail.

E.g. "Yocto now provides their own default DHCP configuration in /lib/..., so drop ours." or so.

2021-09-29 08:48 UTC, rubensfig commented
Updated the commit message.

2021-09-29 10:19 UTC, KanjiMonster approved these changes

2021-09-29 10:19 UTC, merged