Hmag iptables recipe
bisdn/meta-switch pull request #27
Opened 2021-11-03 09:04 UTC by hilmarm

Based on xtables lock MR, but not necessary to have it.

First remove our custom file copying scheme entirely, then readd the bbappend file with a single patch that creates our wanted iptables and ip6tables rule files

2021-11-03 09:06 UTC, hilmarm commented
Two questions,
1: should i drop the first commit with the iptables lock fix, since this is already in the default dunfell recipe?
2: Should i rename the patch prefix to something other than 0001, since the default dunfell recipe already contains three patches, and the prefixes 0001 and 0002 are already used there. In that case, what should I rename the prefix to?

2021-11-03 09:12 UTC, KanjiMonster requested changes
This PR needs a proper title.

Also just remove the parts that copy/install our own service files, and leave the rest intact, I don't think we need to patch those files.

2021-11-03 09:29 UTC, hilmarm commented
> This PR needs a proper title.
> 
> Also just remove the parts that copy/install our own service files, and leave the rest intact, I don't think we need to patch those files.

Edited commits to only remove our custom file additions, then readded the needed patch and entries in bbappend file

2021-11-03 09:31 UTC, KanjiMonster requested changes
No, don't remove the rules files, just keep them. No patches. Just a bbappend that replaces the (empty) rules files.

2021-11-03 13:28 UTC, hilmarm commented
Image built here: http://repo.bisdn.de.s3-eu-central-1.amazonaws.com/latest/accton-as4610/master/onie-bisdn-full-accton-as4610-202111031131.bin

Rebooting older images will quickly fail, as either iptables or ip6tables will fail to start

2021-11-03 13:46 UTC, KanjiMonster requested changes
In general looks okay, but drop the first commit, no point in modifying a file we'll delete right after that.

2021-11-03 13:57 UTC, hilmarm commented
> In general looks okay, but drop the first commit, no point in modifying a file we'll delete right after that.

First commit dropped entirely

2021-11-03 15:00 UTC, KanjiMonster requested changes

2021-11-03 15:00 UTC, KanjiMonster commented on recipes-extended/iptables/iptables_%.bbappend
>  inherit systemd
You probably won't need this one anymore ...

2021-11-03 15:00 UTC, KanjiMonster commented on recipes-extended/iptables/iptables_%.bbappend
>  SYSTEMD_SERVICE_${PN} = "iptables.service ip6tables.service"
since you shouldn't need this anymore.

2021-11-03 15:33 UTC, hilmarm commented
> Have you tested the changes?
> 
> Also please squash fhe commits and drop the (fix) from the commit subject, it should be just ": "

No I am still building the image, commits will be squashed once I finish testing new image

2021-11-03 16:20 UTC, hilmarm commented
Image built and tested with latest changes, ready for re-review.

Test image can be found here:
http://repo.bisdn.de.s3-eu-central-1.amazonaws.com/latest/agema-ag7648/master/onie-bisdn-full-agema-ag7648-202111031604.bin

2021-11-03 16:24 UTC, hilmarm commented on recipes-extended/iptables/iptables_%.bbappend
>  SYSTEMD_SERVICE_${PN} = "iptables.service ip6tables.service"
also removed

2021-11-04 10:24 UTC, KanjiMonster commented
FWIW, this has been added/fixed in yocto itself since dunfell, with commit http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?h=dunfell&id=7a2c2df853934a77a154d254b5d932b9817283f8 (which added the IPv6 helper).

2021-11-04 13:56 UTC, KanjiMonster approved these changes

2021-11-04 13:56 UTC, merged