mstpd: bump version to 0.1.0
bisdn/meta-switch pull request #46
Opened 2022-02-08 14:53 UTC by rubensfig

2022-02-09 09:48 UTC, KanjiMonster requested changes

2022-02-09 09:48 UTC, KanjiMonster commented on recipes-support/mstpd/mstpd_git.bb
> -  file://0002-libnetlink-Set-NLA_F_NESTED-in-rta_nest.patch \
Why are you removing these lines? Please explain in your commit message.

Also please delete the files itself.

2022-02-09 09:48 UTC, KanjiMonster commented on recipes-support/mstpd/mstpd_git.bb
>    file://0004-WIP-set-CIST-MSTI-port-states-to-the-newly-added-per.patch \
And it might make sense to rename these to 0001/0002 then.

2022-02-09 11:17 UTC, KanjiMonster commented
Since we are targeting the 0.1.0 release tag, I think we should rename the recipe to have an actual version instead of just _git

2022-02-09 15:43 UTC, KanjiMonster requested changes
With the mstpd_0.1.0.bb there is no reason for the mstpd_git to exist, so please drop it.

2022-02-11 10:48 UTC, jklare commented on recipes-support/mstpd/mstpd_0.1.0.bb
> +PV = "0.1.0+git${SRCPV}"
```suggestion
PV = "0.1.0+bisdn1"
```

2022-02-17 10:05 UTC, closed without merging